### ISSUE TITLE
Implement Cabal based wrapper

### ISSUE THREAD

**Issue by ivan444** [google/haskell-indexer#13]
The current extractor is using Stack, which is not supported by all Haskell projects. Implement Cabal based extractor to fill the gap.

**Comment by robinp** [comment]
I renamed "extractor -> wrapper" in the bug's description, as we have a separate bug about extractor support. I guess you meant the wrapper script?

**Comment by robinp** [comment]
@gleber did some experimenting in #32 . It also seems possible to tap into Cabal via http://blog.ezyang.com/2017/02/how-to-integrate-ghc-api-programs-with-cabal/, which would make it more robust across old or new build.
