### ISSUE TITLE
No edge from identifier occurrence in type declaration

### ISSUE THREAD

**Issue by ddrone** [google/haskell-indexer#20]
For example,

```haskell
add :: Int -> Int -> Int
add x y = undefined
```

In the first line `add` wouldn't have a reference.

**Comment by robinp** [comment]
Sidenote: I wonder how this relates to typeclass methods? Those methods are similar to declarations, and get specific definitions in instances (to not talk about default methods).

But from Kythe schema's point, typeclasses/instances are more similar to interfaces/implementations, and not sure if the completes/uniquely applies to these in the Kythe schema (rather [overrides](https://kythe.io/docs/schema/#overrides)).

**Comment by creachadair** [comment]
It's important if you want to use the `completes` mechanism to have all the pieces in place. 

@zrlk may have further insights.

**Comment by robinp** [comment]
For the reference there's more Kythe context here: https://kythe.io/docs/schema/callgraph.html#_forward_declarations.

It seems we don't need the `completes` mechanism, as we won't have separate declaration nodes (just the definition ones).

The idea was triggered by haskell's nature of duplicating the binding name in the type signature and the actual implementation, like

```
foo :: Int -> Int
foo a = 5
```
Here we don't get the type sig's `foo` linked now. OTOH, we also don't have multi-clause implementations linked, for example below only the first `bar` has a binding anchor:

```
bar 1 = "fine"
bar _ = "too big"
```
How about (ab) using [`ref/doc`](https://kythe.io/docs/schema/#refdoc) from the typesig anchor?. Types are documentation anyway :)
