### ISSUE TITLE
Make scripts kythe location agnostic

### ISSUE THREAD

**Issue by robinp** [google/haskell-indexer#24]
Now we hardcode `/opt/kythe`, instead we could expect an environment variable. Kythe uses
```KYTHE_ROOT_DIRECTORY``` and ```KYTHE_OUTPUT_DIRECTORY``` in their scripts.

**Comment by MaskRay** [comment]
From `kythe/web/site/examples.md`:
```
# Environment variables common to Kythe extractors
export KYTHE_ROOT_DIRECTORY="$PWD"                        # Root of source code corpus
export KYTHE_OUTPUT_DIRECTORY="/tmp/kythe.compilations/"  # Output directory
export KYTHE_VNAMES="$PWD/kythe/data/vnames.json"         # Optional: VNames configuration
```
`KYTHE_ROOT_DIRECTORY` is not the install prefix of Kythe (e.g. /opt/kythe).

**Comment by robinp** [comment]
@creachadair: is there a suggested env var name for the Kythe installation directory?

**Comment by robinp** [comment]
The kythe examples at least use `KYTHE_RELEASE`, so going with that.
