### ISSUE TITLE
Run as GHC Frontend Plugin

### ISSUE THREAD

**Issue by robinp** [google/haskell-indexer#55]
GHC implements too much administrative magic in `ghc/Main.hs` to replicate them all in `GhcApiSupport`. Should restructure the GHC backend to be a Frontend Plugin rather, which will get (almost all) of the magic. See https://ghc.haskell.org/trac/ghc/ticket/14018#ticket.

Notably, the frontend plugin might still need to decide if it's running in Make or Oneshot mode, and act accordingly. For Make mode this means invoking compileFile on non-Haskell sources and sticking the resulting objects to dflags (see GHC's `doMake` function). No idea for Oneshot.

All this fuss is needed for 1:1 behavior to real GHC invocations. 95% of the time this is not needed, since machine code generation is not needed for indexing most code.

An exception is TemplateHaskell that runs imported function (in which case at least bytecode generation is needed), or when it runs imported FFI-d function (in which case C compilation, machine code generation and linking are needed too). Other exception are some modules that use FFI in particular ways (maybe foreign exports?) which were not content with just generating bytecode. Also, having optimization turned on is not compatible with bytecode gen (but fine with no gen or machine gen). Etc.

+@mpickering FYI.

**Comment by mpickering** [comment]
I completely misunderstood what a frontend plugin was. I thought it was like a core to core plugin which allowed you to run arbitrary transformation passes on typechecked code but in fact it completely replaces the major mode. 

My whole motivation was to avoid having to use any wrappers because as soon as you use a wrapper you also have to specify where ghc-pkg is which is quite tedious. It seems like that can't be avoided for now.

**Comment by robinp** [comment]
Not sure - `cabal new-build` seemed to have a `-w` option which lets you specify an alternative (wrapper) GHC. If you use that, do you still need to mangle/specify separately `ghc-pkg` ?

**Comment by mpickering** [comment]
It depends. It will try to use what is called `ghc-pkg` on your path but this is usually not the right version for me but probably works fine for most people.

**Comment by robinp** [comment]
I wrote about some warts of calling GHC API multiple times at https://gist.github.com/robinp/49c68c6f69f6aabfddee3cba42b4964f. This is not relevant for `ghc-kythe-wrapper`, but can be problematic if one uses the GHC backend in a process that should handle indexing of multiple unrelated compilations.

**Comment by robinp** [comment]
Now it's preferred to use Source Plugins, instead Frontend Plugin. @mpickering might be working on that.

**Comment by robinp** [comment]
Obsolete in favor of the implemented source plugin support.
