### ISSUE TITLE
kythe-proto relies on unbundled storage.proto

### ISSUE THREAD

**Issue by mpickering** [google/haskell-indexer#61]
The build for `kythe-proto` needs access to kythe's storage.proto file. It achieves this by symlinking to `../../../../../third_party/kythe/kythe/proto/storage.proto`. Would it be better to just vendor this specific file? It makes building the package in isolation much more difficult and I had to add some special packaging logic when I packaged it for nix.

**Comment by robinp** [comment]
Sounds good! Would you send a PR? Please mention the Kythe commit the proto is imported from.

**Comment by robinp** [comment]
Fixed in 97131e64c43bf4407914ed55289bb719c26b955d.
