### ISSUE TITLE
Cross-ref Pattern Synonyms

### ISSUE THREAD

**Issue by robinp** [google/haskell-indexer#75]
Both uni and bidirectional.

**Comment by robinp** [comment]
PatSynBind matching has to be added in absFunDeclsFromHsBind (https://github.com/google/haskell-indexer/blob/master/haskell-indexer-backend-ghc/src/Language/Haskell/Indexer/Backend/Ghc.hs#L622).

The psb_id can be used to emit the decl https://downloads.haskell.org/~ghc/8.0.2/docs/html/libraries/ghc-8.0.2/HsBinds.html#t:PatSynBind

ghc-dump-tree on the pattern binding (GHC 8.0.2):

```
## Renamed
( HsGroup
    (ValBindsOut
       [ ( NonRecursive
         , Bag.listToBag
             [ L P.hs:4:1-25
                 (PatSynBind
                    (PSB
                       (L P.hs:4:9-17                        <---- this is the psb_id
                            { n_loc = P.hs:4:1-25
                            , n_sort =  { External = Module main P }
                            , n_uniq = rjG
                            , DataName = Singleton
                            })
                       (UFM (fromList []))
                       (PrefixPatSyn
                          [ L P.hs:4:19
                                { n_loc = P.hs:4:24
                                , n_sort = Internal
                                , n_uniq = alL
                                , VarName = e
                                }
                          ])
                       (L P.hs:4:23-25
                          (ListPat
                             [ L P.hs:4:24
                                 (VarPat
                                      { n_loc = P.hs:4:24
                                      , n_sort = Internal
                                      , n_uniq = alL
                                      , VarName = e
                                      })
                             ]
                             PlaceHolder
                             Nothing))
                       ImplicitBidirectional))
             ]
```

Referring the pattern: I would expect this to already work once the decl is emitted above, but including AST for completeness.

```
             [ L P.hs:(6,1)-(7,10)
                 (FunBind
                    (L P.hs:6:1-3
                         { n_loc = P.hs:6:1-3
                         , n_sort =  { External = Module main P }
                         , n_uniq = rlx
                         , VarName = foo
                         })
                    False
                    (MG
                       [ L P.hs:6:1-23
                           (Match
                              (Just
                                 ( L P.hs:6:1-3
                                       { n_loc = P.hs:6:1-3
                                       , n_sort =  { External = Module main P }
                                       , n_uniq = rlx
                                       , VarName = foo
                                       }
                                 , False
                                 ))
                              [ L P.hs:6:5-17
                                  (ParPat
                                     (L P.hs:6:6-16
                                        (ConPatIn
                                           (L P.hs:6:6-14
                                                { n_loc = P.hs:4:1-25
                                                , n_sort =  { External = Module main P }
                                                , n_uniq = rjG
                                                , DataName = Singleton
                                                })
                                           (PrefixCon
                                              [ L P.hs:6:16
                                                  (VarPat
                                                       { n_loc = P.hs:6:16
                                                       , n_sort = Internal
                                                       , n_uniq = am1
                                                       , VarName = a
                                                       })
                                              ]))))
                              ]
```

**Comment by cbiffle** [comment]
Thanks for the pointer to `absFunDeclsFromHsBind`, but are you sure about its role here? I ask because inserting

```haskell
        PatSynBind p -> error "lol"
```

in that case statement doesn't cause anything to fail, even when I feed it a file containing pattern synonyms from my [test case](https://github.com/cbiffle/haskell-indexer/commit/970d46dad64ff31b15a9d0578026e3a8f6cef9c2). `concatMap` should evaluate the spine of the list and hit that bottom if it's matching...

**Comment by robinp** [comment]
@cbiffle : You are right. I don't have ghc-dump-tree at hand, but that part of the indexer takes declarations from the Typechecked source, while I pasted the Renamed source (both are dumped by ghc-dump-tree).

Colud you try and see how is the PatSynBind organized in the Typechecked source (maybe under an AbsBind?), and make modifications in the Parent pattern matching of https://github.com/google/haskell-indexer/blob/master/haskell-indexer-backend-ghc/src/Language/Haskell/Indexer/Backend/Ghc.hs#L600 accordingly.

**Comment by robinp** [comment]
I had a look on the tree:


Decl in renamed (with slightly patched ghc-dump-tree to expand the PatSynBind):

```
## Renamed
( HsGroup
    (ValBindsOut
       [ ( NonRecursive
         , Bag.listToBag
             [ L P.hs:4:1-25
                 (PatSynBind
                    (PSB
                       (L P.hs:4:9-17
                            { n_loc = P.hs:4:1-25                 <----------------- this is unLoc . psb_id.
                            , n_sort =  { External = Module main P }
                            , n_uniq = rjG
                            , DataName = Singleton
                            })
                       (UFM (fromList []))
                       (PrefixPatSyn
                          [ L P.hs:4:19
                                { n_loc = P.hs:4:24
                                , n_sort = Internal
                                , n_uniq = am0
                                , VarName = e
                                }
                          ])
                       (L P.hs:4:23-25
                          (ListPat
                             [ L P.hs:4:24
                                 (VarPat
                                      { n_loc = P.hs:4:24
                                      , n_sort = Internal
                                      , n_uniq = am0
                                      , VarName = e
                                      })
                             ]
                             PlaceHolder
                             Nothing))
                       ImplicitBidirectional))
             ]
         )
```

Ref in the typechecked:

```
(MG
                      [ L P.hs:6:1-23
                          (Match
                             Nothing
                             [ L P.hs:6:5-17
                                 (ParPat
                                    (L P.hs:6:6-16
                                       (ConPatOut
                                          (L P.hs:6:6-14
                                             PatSynCon
                                               { name =            <---- this is psName of PatSyn in the ConLike
                                                     { n_loc = P.hs:4:1-25
                                                     , n_sort =  { External = Module main P }
                                                     , n_uniq = rjG
                                                     , DataName = Singleton
                                                     }
                                               })
                                          [   { t =
                                                  TyVarTy
                                                      { varType =  { * = TyConApp * [] }
                                                      , n_loc = P.hs:(6,1)-(7,10)
                                                      , n_sort = Internal
                                                      , n_uniq = amf
                                                      , TvName = t
                                                      }
                                              }
                                          ]
```

I'm showing the decl in the Renamed tree, since PatSyn seems to be represented more like classes & instances with lot of wrappers in the Typechecked tree.

So I would advise to extract the decl from the Renamed tree. I expect the ref to be extracted already.

**Comment by cbiffle** [comment]
Alright, so. The test passes as of [this commit](https://github.com/cbiffle/haskell-indexer/commit/d2c8922b32b29952f815997258998a7bf963efc6). It's ugly and I'm interested in any advice on how to make it less so. (I have also stubbed out the support for versions of GHC prior to 8, for the time being.)

The situation:

The indexer, before I got to it, was generating decls for pattern synonyms from the typechecked tree.

- A uni-directional synonym `Foo` got a decl `$mFoo`.
- A bi-directional synonym `Foo` got decls `$bFoo` and $mFoo` (in that order, which is significant below).

The `$bFoo` decl is correctly ref'd when the pattern synonym is employed in an expression context. The `$mFoo` decls are never ref'd by the indexer.

In that commit, I added code to generate an additional decl from the renamed tree, which simply has name `Foo`. Your suspicion that the refs were already being generated when pattern synonyms were employed in pattern context was *correct*; with the un-decorated `Foo` decl from the renamed tree, the refs work.

In expression context, the `$bFoo` decl is still ref'd, and the `$mFoo` decl is never ref'd. You can see this oddity in my test case (and my apologetic comments therein). It would seem substantially cleaner if the indexer did not generate decls for pattern synonyms from the typechecked tree, and instead directed all refs of a pattern synonym to the un-decorated decl produced from the renamed tree. I am not, however, sure how to do this.

(Out of curiosity: so refs that don't match a decl aren't treated as errors, eh? I bet there are other cases like this.)

Thanks in advance.

**Comment by robinp** [comment]
As for refs without a decl: that's normal on the cross-module level, as refs can be emitted for decls that are emitted only when that other module is indexed (maybe in an other package). Two remarks:

  1. Indeed it would be a nice global consistency check to get these dangling refs.
  2. For a ref targeting the local module though, a dangling ref is surely fishy.

Opened #77

**Comment by robinp** [comment]
Interesting, the `$bFoo` decl is indeed not directly relatable with the `Foo` decl.

What you could do, is go over the collected decls from the renamed/typechecked tree, match up the two based on the tickLocation (which seem to span the same full lines), and combine then into a single `DeclAndAlt` where the decl part is from the renamed tree, the alt part is `$bFoo` from the typechecked.

That way refs for the latter will be retargeted to the former. The location-based matching is not ideal, but I don't see better for now.

**Comment by jinwoo** [comment]
I'll take a stab at this.

**Comment by jinwoo** [comment]
I encountered the same problem where both `Foo` and `$mFoo` (and also `$bFoo` in case of bi-directional synonyms) exist. `$mFoo` and `$bFoo` decls are created from the generated code: https://github.com/google/haskell-indexer/blob/master/haskell-indexer-backend-ghc/src/Language/Haskell/Indexer/Backend/Ghc.hs#L595

So I should figure out how to *not* create those decls from generated code.

**Comment by jinwoo** [comment]
I could do that by extending the `SpecialVar` data and the `specialVar` function to include the `$m` and `$b` cases:
https://github.com/google/haskell-indexer/blob/master/haskell-indexer-backend-ghc/src/Language/Haskell/Indexer/Backend/Ghc.hs#L698
