### ISSUE TITLE
http://stuff.codereview.me/lts/9.2/ down or slow?

### ISSUE THREAD

**Issue by nh2** [google/haskell-indexer#78]
Hey @robinp,

I can't load http://stuff.codereview.me/lts/9.2/ currently, it seems to load extremely slowly and after 2 minutes times out (some resources do seem to load eventually).

Could you have a look if that should still be working?

Thanks!

**Comment by robinp** [comment]
My bad, I stopped the instance. It's back!

**Comment by nh2** [comment]
Thanks!

**Comment by nh2** [comment]
@robinp It's down again

**Comment by robinp** [comment]
Sorry, the shell gnomes stopped the server again. Running, wrapped it in a magical while loop.
