### ISSUE TITLE
Update to GHC-8.4.3

### ISSUE THREAD

**Issue by mpickering** [google/haskell-indexer#80]
The necessary changes are on the branch on my repo - https://github.com/mpickering/haskell-indexer/tree/ghc-8.4.3

It's possible that https://github.com/mpickering/haskell-indexer/commit/ae09b7ff7944887e06abca16ba297a504ed8ffd7 can be cherry-picked without the other changes.

**Comment by robinp** [comment]
Thanks! the mentioned commit looks ok (left a comment), could you try a PR? Please also add GHC 8.4 to the .travis.yml in the repo root, so we see if CI is happy about it.
