### ISSUE TITLE
Index haskell through a GHC source plugin

### ISSUE THREAD

**Issue by facundominguez** [google/haskell-indexer#88]
Currently, `haskell-indexer` needs to be integrated with each of various build systems. It needs to be concerned with loading the code with the GHC API with appropriate flags so it can be indexed.

This issue is about indexing from a [source plugin](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/extending_ghc.html#source-plugins) instead.

This would remove from `haskell-indexer` the burden of dealing with the GHC API to parse the code and to load code dependencies. The user would only need to arrange `-fplugin Language.Haskell.Indexer` to be passed to all invocations of GHC during a regular build of whatever build system she has in place. This should remove most of the build configuration problems that could make `haskell-indexer` fail, and would probably remove the need to use and maintain ghc wrappers.

Note that there was a former issue (#55) for implementing a frontend plugin, which is something different.

I'm not very acquainted with kythe or `haskell-indexer` yet, but I'm curious about whether the source plugin idea is as good as it sound from the outside.

**Comment by mpickering** [comment]
I implemented this at Munihac. I'll post a PR this week.
