### ISSUE TITLE
Remove support for GHC < 8.6

### ISSUE THREAD

**Issue by jinwoo** [google/haskell-indexer#98]
8.0.1 is 3+ years old and it's a maintenance burden. Let's delete conditional code for 8.0.x and the CI setup.

@robinp What do you think?

**Comment by robinp** [comment]
Sounds good!

**Comment by jinwoo** [comment]
Thanks, Robin. Judah and I also discussed on removing all the versions < 8.6 because the GHC API changed a lot in 8.6 (many type signatures changed and new data constructors were added), and it is also a big maintenance burden.

We could leave only 8.6 and also add 8.8 later. I saw you thumbed up in that discussion, so I assume you're fine with that. I'm going to change the title of this issue.

**Comment by judah** [comment]
FY, supporting 8.8 will probably be blocked on the relevant support in proto-lens: google/proto-lens#341.

**Comment by jinwoo** [comment]
Ah, Thanks, Judah. Then we'll probably have to do 8.8 later.
